Update build-gki-kowsu.yml

diff --git a/.github/workflows/build-gki-kowsu.yml b/.github/workflows/build-gki-kowsu.yml
--- a/.github/workflows/build-gki-kowsu.yml
+++ b/.github/workflows/build-gki-kowsu.yml
@@ -187,7 +187,13 @@ jobs:
       if: env.PIXEL8A == 'y'
       working-directory: ${{ env.KERNEL_DIR }}
       run: |
-        CONFIG="${{ env.CONFIG_FILE }}"
+        
+       CONFIG="$KERNEL_DIR/arch/arm64/configs/gki_defconfig"
+
+       if [ ! -f "$CONFIG" ]; then
+       echo "❌ gki_defconfig not found: $CONFIG"
+       exit 1
+       fi
         
         # Add Pixel 8a specific configurations
         cat >> "$CONFIG" << EOF
